### ISSUE TITLE
Missing else when food could not appear on snake

### ISSUE THREAD

**Issue by GrosSacASac** [filipeportes/snake-game#2]
https://github.com/filipeportes/snake-game/blob/master/snake.js#L40

**Comment by filipeportes** [comment]
I'm just checking if the random food coordinates are not inside the snake body, in the else case I just keep the coordinates.

**Comment by GrosSacASac** [comment]
Does that mean the snake immediately eats again ?

**Comment by filipeportes** [comment]
no, this method generates a new food coordinate in the startup or after one is eaten, I just want to avoid generating the food in some place where the snake already is.

food is added in the snake body here: https://github.com/filipeportes/snake-game/blob/master/snake.js#L89
